name: Ejecutar scraper cada 3 horas

on:
  schedule:
    - cron: "0 */3 * * *"  # Ejecuta cada 3 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Mostrar hora actual (Debug)
        run: date

      - name: Configurar credenciales
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Verificar archivo de credenciales (Debug)
        run: cat credentials.json || echo "El archivo no se generó correctamente"

      - name: Ejecutar el script
        run: python scraper.py
